services:
  project_hud:
    image: project_hud:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/New_York
      GITHUB_TOKEN:
      GITHUB_REPOS:
      USERNAME_MAP:
      ADMIN_PASSWORD:
      DATABASE_PATH: /app/data/projecthud.db
    volumes:
      - project_hud_data:/app/data
    restart: "no"
    command: "true"

volumes:
  project_hud_data:
